let storesTurkey = [
  {
    recommendation: {},
    storeNumber: "54517-286757",
    id: "1021623",
    name: "Mimaroba",
    phoneNumber: null,
    coordinates: { latitude: 40.996809, longitude: 28.540567 },
    regulations: [],
    address: {
      streetAddressLine1: "Bahadir Sok.",
      streetAddressLine2: "Buyukcekmece",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34535",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: ["Bahadir Sok.", "Buyukcekmece", "Istanbul, 34 34535"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "mimaroba-bahadir-sok-istanbul-34-34535-tr",
  },
  {
    recommendation: {},
    storeNumber: "50078-272728",
    id: "1017111",
    name: "Beykent 53",
    phoneNumber: null,
    coordinates: { latitude: 40.995493, longitude: 28.625888 },
    regulations: [],
    address: {
      streetAddressLine1: "Adnan Kahveci Mah. Yavuz Sultan",
      streetAddressLine2: "Selim Bulvari .NO:53A Beylikduzu",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34528",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Adnan Kahveci Mah. Yavuz Sultan",
      "Selim Bulvari .NO:53A Beylikduzu",
      "Istanbul, 34 34528",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "beykent-53-adnan-kahveci-mah-yavuz-sultan-istanbul-34-34528-t",
  },
  {
    recommendation: {},
    storeNumber: "52806-283172",
    id: "1019445",
    name: "O86 BURSA KUZEY",
    phoneNumber: null,
    coordinates: { latitude: 40.231799, longitude: 28.779319 },
    regulations: [],
    address: {
      streetAddressLine1: "Istanbul- Izmir Otoyolu 86.km",
      streetAddressLine2: "o86 shopping center",
      streetAddressLine3: null,
      city: "Bursa",
      countrySubdivisionCode: "16",
      countryCode: "TR",
      postalCode: "16110",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Istanbul- Izmir Otoyolu 86.km",
      "o86 shopping center",
      "Bursa, 16 16110",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "o-86-bursa-kuzey-istanbul-izmir-otoyolu-86-km-bursa-16-16110-tr",
  },
  {
    recommendation: {},
    storeNumber: "52796-283173",
    id: "1019443",
    name: "O86 BURSA GUNEY",
    phoneNumber: null,
    coordinates: { latitude: 40.231406, longitude: 28.782323 },
    regulations: [],
    address: {
      streetAddressLine1: "Istanbul- Izmir Otoyolu 86.km",
      streetAddressLine2: "o86 shopping center",
      streetAddressLine3: null,
      city: "Bursa",
      countrySubdivisionCode: "16",
      countryCode: "TR",
      postalCode: "16110",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Istanbul- Izmir Otoyolu 86.km",
      "o86 shopping center",
      "Bursa, 16 16110",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "o-86-bursa-guney-istanbul-izmir-otoyolu-86-km-bursa-16-16110-tr",
  },
  {
    recommendation: {},
    storeNumber: "57091-291103",
    id: "1023974",
    name: "Buyukcekmece Sahil",
    phoneNumber: null,
    coordinates: { latitude: 41.016082, longitude: 28.592596 },
    regulations: [],
    address: {
      streetAddressLine1: "Kordonboyu Cad",
      streetAddressLine2: "Buyukcekmece",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34500",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: ["Kordonboyu Cad", "Buyukcekmece", "Istanbul, 34 34500"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "buyukcekmece-sahil-kordonboyu-cad-istanbul-34-34500-tr",
  },
  {
    recommendation: {},
    storeNumber: "50073-272726",
    id: "1017109",
    name: "Beylikduzu Teras Park",
    phoneNumber: null,
    coordinates: { latitude: 41.003482, longitude: 28.637593 },
    regulations: [],
    address: {
      streetAddressLine1: "Adnan Kahveci Mah. Ataturk Bulvari",
      streetAddressLine2: "N0: 20 Teras Park Avm Beylikduzu",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34528",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Adnan Kahveci Mah. Ataturk Bulvari",
      "N0: 20 Teras Park Avm Beylikduzu",
      "Istanbul, 34 34528",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "beylikduzu-teras-park-adnan-kahveci-mah-ataturk-bulvari-istanbul-34-3452",
  },
  {
    recommendation: {},
    storeNumber: "48175-261867",
    id: "1015320",
    name: "Beykent",
    phoneNumber: null,
    coordinates: { latitude: 41.010634, longitude: 28.625856 },
    regulations: [],
    address: {
      streetAddressLine1: "Yavuz Sultan Selim Blv Hilal Konaklari",
      streetAddressLine2: "Site C2 Apt No 32AA Buyukcekmece",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "000000",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Yavuz Sultan Selim Blv Hilal Konaklari",
      "Site C2 Apt No 32AA Buyukcekmece",
      "Istanbul, 34 000000",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "beykent-yavuz-sultan-selim-blv-hilal-konaklari-istanbul-34",
  },
  {
    recommendation: {},
    storeNumber: "55359-289213",
    id: "1022277",
    name: "Beylikduzu Yasam",
    phoneNumber: null,
    coordinates: { latitude: 41.005265, longitude: 28.653641 },
    regulations: [],
    address: {
      streetAddressLine1: "Kir Sokak",
      streetAddressLine2: "Beylikduzu",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34520",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: ["Kir Sokak", "Beylikduzu", "Istanbul, 34 34520"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "beylikduzu-yasam-kir-sokak-istanbul-34-34520-tr",
  },
  {
    recommendation: {},
    storeNumber: "1950-138064",
    id: "6042",
    name: "Starbucks",
    phoneNumber: "0 212 853 45 06",
    coordinates: { latitude: 41.0079, longitude: 28.6582 },
    regulations: [],
    address: {
      streetAddressLine1: "Baris Mah. E-5 Karayolu Sakaya Cad. 5M",
      streetAddressLine2: "MIGROS No:1 K:Giris D:CZ15",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34520",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: true,
    openStatusText: "Open until 10:00 PM",
    addressLines: [
      "Baris Mah. E-5 Karayolu Sakaya Cad. 5M",
      "MIGROS No:1 K:Giris D:CZ15",
      "Istanbul, 34 34520",
    ],
    mop: { ready: false, wait: null },
    schedule: [
      {
        dayName: "Today",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tomorrow",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sunday",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Monday",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tuesday",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Wednesday",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Thursday",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
    ],
    features: [],
    slug: "starbucks-baris-mah-e-5-karayolu-sakaya-cad-5-m-istanbul-34-",
  },
  {
    recommendation: {},
    storeNumber: "56853-290817",
    id: "1027507",
    name: "Avenue Beykent",
    phoneNumber: null,
    coordinates: { latitude: 41.019924, longitude: 28.627854 },
    regulations: [],
    address: {
      streetAddressLine1: "Avrupa Caddesi",
      streetAddressLine2: "Buyukcekmece",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34500",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: ["Avrupa Caddesi", "Buyukcekmece", "Istanbul, 34 34500"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "avenue-beykent-avrupa-caddesi-istanbul-34-34500-tr",
  },
  {
    recommendation: {},
    storeNumber: "50657-275326",
    id: "1017543",
    name: "Beylikduzu Cumhuriyet",
    phoneNumber: null,
    coordinates: { latitude: 41.017433, longitude: 28.64428 },
    regulations: [],
    address: {
      streetAddressLine1: "Cumhuriyet mah. Cumhuriyet Cad",
      streetAddressLine2: "No:3 Beylikduzu",
      streetAddressLine3: null,
      city: "ISTANBUL",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34515",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Cumhuriyet mah. Cumhuriyet Cad",
      "No:3 Beylikduzu",
      "ISTANBUL, 34 34515",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "beylikduzu-cumhuriyet-cumhuriyet-mah-cumhuriyet-cad-istanbul-34-34515-tr",
  },
  {
    recommendation: {},
    storeNumber: "15825-165246",
    id: "52060",
    name: "Starbucks",
    phoneNumber: "0 212 596 32 66",
    coordinates: { latitude: 41.003759, longitude: 28.688172 },
    regulations: [],
    address: {
      streetAddressLine1: "Saadetdere Mah. 68. Sok. Torium",
      streetAddressLine2: "No:50 K:4 D:263",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34513",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: true,
    openStatusText: "Open until 10:00 PM",
    addressLines: [
      "Saadetdere Mah. 68. Sok. Torium",
      "No:50 K:4 D:263",
      "Istanbul, 34 34513",
    ],
    mop: { ready: false, wait: null },
    schedule: [
      {
        dayName: "Today",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tomorrow",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sunday",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Monday",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tuesday",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Wednesday",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Thursday",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
    ],
    features: [],
    slug: "starbucks-saadetdere-mah-68-sok-torium-istanbul-34-34513-tr",
  },
  {
    recommendation: {},
    storeNumber: "59076-293251",
    id: "1025586",
    name: "Firuzkoy",
    phoneNumber: null,
    coordinates: { latitude: 40.99285, longitude: 28.717663 },
    regulations: [],
    address: {
      streetAddressLine1: "Firuzkoy Bulvari",
      streetAddressLine2: "Universite Mahallesi, Avclar",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34320",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Firuzkoy Bulvari",
      "Universite Mahallesi, Avclar",
      "Istanbul, 34 34320",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "firuzkoy-firuzkoy-bulvari-istanbul-34-34320-tr",
  },
  {
    recommendation: {},
    storeNumber: "57576-291713",
    id: "1027588",
    name: "Haramidere",
    phoneNumber: null,
    coordinates: { latitude: 41.008715, longitude: 28.681512 },
    regulations: [],
    address: {
      streetAddressLine1: "Adile Nasit Bulvari",
      streetAddressLine2: "Zafer Mahallesi",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34513",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Adile Nasit Bulvari",
      "Zafer Mahallesi",
      "Istanbul, 34 34513",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "haramidere-adile-nasit-bulvari-istanbul-34-34513-tr",
  },
  {
    recommendation: {},
    storeNumber: "17620-186185",
    id: "92623",
    name: "Starbucks",
    phoneNumber: null,
    coordinates: { latitude: 40.966087, longitude: 28.797278 },
    regulations: [],
    address: {
      streetAddressLine1: "Senlikkoy Mah. Yesilkoy Halkali Cad.",
      streetAddressLine2: "No : 93 Florya / Ist",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34154",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Senlikkoy Mah. Yesilkoy Halkali Cad.",
      "No : 93 Florya / Ist",
      "Istanbul, 34 34154",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "starbucks-senlikkoy-mah-yesilkoy-halkali-cad-istanbul-34-341",
  },
  {
    recommendation: {},
    storeNumber: "20117-203437",
    id: "1005980",
    name: "Starbucks",
    phoneNumber: null,
    coordinates: { latitude: 40.222186, longitude: 28.850317 },
    regulations: [],
    address: {
      streetAddressLine1: "Sakarya Mah. Atatürk Cad. Gorukle Trio",
      streetAddressLine2: "Yasam Merkezi No:101 D:B08",
      streetAddressLine3: null,
      city: "Bursa",
      countrySubdivisionCode: "16",
      countryCode: "TR",
      postalCode: "16285",
    },
    timeZoneInfo: {
      currentTimeOffset: 120,
      windowsTimeZoneId: "Central Europe Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Sakarya Mah. Atatürk Cad. Gorukle Trio",
      "Yasam Merkezi No:101 D:B08",
      "Bursa, 16 16285",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "starbucks-sakarya-mah-ataturk-cad-gorukle-trio-bursa-16-1628",
  },
  {
    recommendation: {},
    storeNumber: "48996-266342",
    id: "1016231",
    name: "Yesilkoy Cadde",
    phoneNumber: null,
    coordinates: { latitude: 40.958534, longitude: 28.821818 },
    regulations: [],
    address: {
      streetAddressLine1: "Istasyon Cad. Yesilkoy",
      streetAddressLine2: "Bakirkoy",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "0000",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: ["Istasyon Cad. Yesilkoy", "Bakirkoy", "Istanbul, 34 0000"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "yesilkoy-cadde-istasyon-cad-yesilkoy-istanbul-34-0000-tr",
  },
  {
    recommendation: {},
    storeNumber: "42505-94049",
    id: "6007",
    name: "Starbucks",
    phoneNumber: "00902125732348",
    coordinates: { latitude: 40.973001, longitude: 28.804333 },
    regulations: [],
    address: {
      streetAddressLine1: "Senlik Mah. Yesilkoy Asfalti Harman Sok.",
      streetAddressLine2: "Flyinn Alisveris Yasam Merk.No:48 K:1D73",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34153",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: true,
    openStatusText: "Open until 10:00 PM",
    addressLines: [
      "Senlik Mah. Yesilkoy Asfalti Harman Sok.",
      "Flyinn Alisveris Yasam Merk.No:48 K:1D73",
      "Istanbul, 34 34153",
    ],
    mop: { ready: false, wait: null },
    schedule: [
      {
        dayName: "Today",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tomorrow",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sunday",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Monday",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tuesday",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Wednesday",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Thursday",
        hours: "10:00 AM to 10:00 PM",
        open: true,
        holiday: "",
      },
    ],
    features: [],
    slug: "starbucks-senlik-mah-yesilkoy-asfalti-harman-sok-istanbul-34",
  },
  {
    recommendation: {},
    storeNumber: "31006-201892",
    id: "1005183",
    name: "Starbucks",
    phoneNumber: "212 4653211",
    coordinates: { latitude: 40.977768, longitude: 28.819776 },
    regulations: [],
    address: {
      streetAddressLine1: "Ataturk Havalimani, Departures",
      streetAddressLine2: "Yesilköy",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34149",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Ataturk Havalimani, Departures",
      "Yesilköy",
      "Istanbul, 34 34149",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "starbucks-ataturk-havalimani-departures-istanbul-34-34149-tr",
  },
  {
    recommendation: {},
    storeNumber: "30952-101377",
    id: "5949",
    name: "Starbucks",
    phoneNumber: "212 4650977",
    coordinates: { latitude: 40.977768, longitude: 28.819866 },
    regulations: [],
    address: {
      streetAddressLine1: "Ataturk Havalimani",
      streetAddressLine2: "Yesilkoy",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34149",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: ["Ataturk Havalimani", "Yesilkoy", "Istanbul, 34 34149"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "starbucks-ataturk-havalimani-istanbul-34-34149-tr",
  },
  {
    recommendation: {},
    storeNumber: "13170-154965",
    id: "19227",
    name: "Starbucks",
    phoneNumber: "212 4650125",
    coordinates: { latitude: 40.980356, longitude: 28.816473 },
    regulations: [],
    address: {
      streetAddressLine1: "Ataturk Havalimani D: DAD/136",
      streetAddressLine2: "Yesilkoy",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34149",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: true,
    openStatusText: "Open 24 hours",
    addressLines: [
      "Ataturk Havalimani D: DAD/136",
      "Yesilkoy",
      "Istanbul, 34 34149",
    ],
    mop: { ready: false, wait: null },
    schedule: [
      {
        dayName: "Today",
        hours: "12:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tomorrow",
        hours: "12:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sunday",
        hours: "12:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Monday",
        hours: "12:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tuesday",
        hours: "12:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Wednesday",
        hours: "12:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Thursday",
        hours: "12:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
    ],
    features: [
      {
        code: "hrs24",
        name: "Open 24 hours per day",
        filterable: true,
        public: true,
      },
    ],
    slug: "starbucks-ataturk-havalimani-d-dad-136-istanbul-34-34149-tr",
  },
  {
    recommendation: {},
    storeNumber: "48716-264856",
    id: "1015876",
    name: "Bursa Balat",
    phoneNumber: null,
    coordinates: { latitude: 40.266222, longitude: 28.939366 },
    regulations: [],
    address: {
      streetAddressLine1: "Ahmet Yesevi Mah. Balat Cad.",
      streetAddressLine2: "No:2 Nilufer Bursa",
      streetAddressLine3: null,
      city: "Bursa",
      countrySubdivisionCode: "16",
      countryCode: "TR",
      postalCode: "00000",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Ahmet Yesevi Mah. Balat Cad.",
      "No:2 Nilufer Bursa",
      "Bursa, 16 00000",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "bursa-balat-ahmet-yesevi-mah-balat-cad-bursa-16-00000-tr",
  },
  {
    recommendation: {},
    storeNumber: "15922-165245",
    id: "66373",
    name: "Starbucks",
    phoneNumber: "212 3977061",
    coordinates: { latitude: 41.05571, longitude: 28.6661 },
    regulations: [],
    address: {
      streetAddressLine1: "Sanayi Mah. 1655. Sok. Akbati Alisveris",
      streetAddressLine2: "ve Yasam Merkezi No: 6 K: 1 D: 64",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34517",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: true,
    openStatusText: "Open until 11:00 PM",
    addressLines: [
      "Sanayi Mah. 1655. Sok. Akbati Alisveris",
      "ve Yasam Merkezi No: 6 K: 1 D: 64",
      "Istanbul, 34 34517",
    ],
    mop: { ready: false, wait: null },
    schedule: [
      {
        dayName: "Today",
        hours: "9:00 AM to 11:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tomorrow",
        hours: "9:00 AM to 11:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sunday",
        hours: "9:00 AM to 11:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Monday",
        hours: "9:00 AM to 11:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tuesday",
        hours: "9:00 AM to 11:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Wednesday",
        hours: "9:00 AM to 11:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Thursday",
        hours: "9:00 AM to 11:00 PM",
        open: true,
        holiday: "",
      },
    ],
    features: [],
    slug: "starbucks-sanayi-mah-1655-sok-akbati-alisveris-istanbul-34-3",
  },
  {
    recommendation: {},
    storeNumber: "28107-247536",
    id: "1014593",
    name: "Endulus Park",
    phoneNumber: null,
    coordinates: { latitude: 40.26749, longitude: 28.94805 },
    regulations: [],
    address: {
      streetAddressLine1: "Ahmet Yesevi Mh. Sanayi Cd.",
      streetAddressLine2: "No : 451 Balat, Nilufer",
      streetAddressLine3: null,
      city: "Bursa",
      countrySubdivisionCode: "16",
      countryCode: "TR",
      postalCode: "16140",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Ahmet Yesevi Mh. Sanayi Cd.",
      "No : 451 Balat, Nilufer",
      "Bursa, 16 16140",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "endulus-park-ahmet-yesevi-mh-sanayi-cd-bursa-16-16140-tr",
  },
  {
    recommendation: {},
    storeNumber: "31465-106826",
    id: "6017",
    name: "Starbucks",
    phoneNumber: "00902124657080",
    coordinates: { latitude: 40.985979, longitude: 28.831376 },
    regulations: [],
    address: {
      streetAddressLine1: "Yesilkoy Mah. Ataturk Cad Istanbul Dunya",
      streetAddressLine2: "Ticaret Merkezi K: Zemin D: 57-58-59",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34149",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Yesilkoy Mah. Ataturk Cad Istanbul Dunya",
      "Ticaret Merkezi K: Zemin D: 57-58-59",
      "Istanbul, 34 34149",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "starbucks-yesilkoy-mah-ataturk-cad-istanbul-dunya-istanbul-3",
  },
  {
    recommendation: {},
    storeNumber: "57378-291481",
    id: "1023817",
    name: "Hadimkoy",
    phoneNumber: null,
    coordinates: { latitude: 41.074347, longitude: 28.622518 },
    regulations: [],
    address: {
      streetAddressLine1: "Hadimkoy Yolu Caddesi",
      streetAddressLine2: "Alkent 2000 Mahallesi",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34522",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Hadimkoy Yolu Caddesi",
      "Alkent 2000 Mahallesi",
      "Istanbul, 34 34522",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "hadimkoy-hadimkoy-yolu-caddesi-istanbul-34-34522-tr",
  },
  {
    recommendation: {},
    storeNumber: "54952-288731",
    id: "1022131",
    name: "Ertugrulkent",
    phoneNumber: null,
    coordinates: { latitude: 40.226042, longitude: 28.90728 },
    regulations: [],
    address: {
      streetAddressLine1: "Zambak sokak",
      streetAddressLine2: "Nilufer",
      streetAddressLine3: null,
      city: "Bursa",
      countrySubdivisionCode: "16",
      countryCode: "TR",
      postalCode: "16440",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: ["Zambak sokak", "Nilufer", "Bursa, 16 16440"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "ertugrulkent-zambak-sokak-bursa-16-16440-tr",
  },
  {
    recommendation: {},
    storeNumber: "54963-288729",
    id: "1021842",
    name: "A Ofis Atakoy",
    phoneNumber: null,
    coordinates: { latitude: 40.991956, longitude: 28.826832 },
    regulations: [],
    address: {
      streetAddressLine1: "D100 Guney Yan yolu",
      streetAddressLine2: "Bakirkoy",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34158",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: ["D100 Guney Yan yolu", "Bakirkoy", "Istanbul, 34 34158"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "a-ofis-atakoy-d-100-guney-yan-yolu-istanbul-34-34158-tr",
  },
  {
    recommendation: {},
    storeNumber: "1495-152925",
    id: "18920",
    name: "Starbucks",
    phoneNumber: "212 5593800",
    coordinates: { latitude: 40.978481, longitude: 28.85031 },
    regulations: [],
    address: {
      streetAddressLine1: "6. Kisim Adnan Kahveci Bulv. Atakoy Plus",
      streetAddressLine2: "Alisveris Merkezi No 3 K: Zemin D ZK2-10",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34158",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: true,
    openStatusText: "Open until 12:00 AM",
    addressLines: [
      "6. Kisim Adnan Kahveci Bulv. Atakoy Plus",
      "Alisveris Merkezi No 3 K: Zemin D ZK2-10",
      "Istanbul, 34 34158",
    ],
    mop: { ready: false, wait: null },
    schedule: [
      {
        dayName: "Today",
        hours: "9:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tomorrow",
        hours: "9:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sunday",
        hours: "9:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Monday",
        hours: "9:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tuesday",
        hours: "9:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Wednesday",
        hours: "9:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Thursday",
        hours: "9:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
    ],
    features: [],
    slug: "starbucks-6-kisim-adnan-kahveci-bulv-atakoy-plus-istanbul-34",
  },
  {
    recommendation: {},
    storeNumber: "27402-247535",
    id: "1014224",
    name: "Ardic Park",
    phoneNumber: null,
    coordinates: { latitude: 40.226082, longitude: 28.914869 },
    regulations: [],
    address: {
      streetAddressLine1: "Ertugrul Mh. Ahmet Taner Kislali Bulvari",
      streetAddressLine2: "Nilufer",
      streetAddressLine3: null,
      city: "Bursa",
      countrySubdivisionCode: "16",
      countryCode: "TR",
      postalCode: "16110",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Ertugrul Mh. Ahmet Taner Kislali Bulvari",
      "Nilufer",
      "Bursa, 16 16110",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "ardic-park-ertugrul-mh-ahmet-taner-kislali-bulvari-bursa-16-1",
  },
  {
    recommendation: {},
    storeNumber: "23121-228066",
    id: "1009346",
    name: "Starbucks",
    phoneNumber: null,
    coordinates: { latitude: 41.01989, longitude: 28.781941 },
    regulations: [],
    address: {
      streetAddressLine1: "Besyol Mah. Inonu Cad. No: 38",
      streetAddressLine2: "Sefakoy / Kucukcekmece",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34295",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Besyol Mah. Inonu Cad. No: 38",
      "Sefakoy / Kucukcekmece",
      "Istanbul, 34 34295",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "starbucks-besyol-mah-inonu-cad-no-38-istanbul-34-34295-tr",
  },
  {
    recommendation: {},
    storeNumber: "31412-107164",
    id: "6023",
    name: "Starbucks",
    phoneNumber: "0 212 465 83 68",
    coordinates: { latitude: 40.992281, longitude: 28.832085 },
    regulations: [],
    address: {
      streetAddressLine1: "9. ve 10. Kisim Istanbul Kultur",
      streetAddressLine2: "Universitesi D-100 Yanyol K:-1",
      streetAddressLine3: null,
      city: "Istanbul - Avrupa",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34158",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: false,
    openStatusText: "Closed",
    addressLines: [
      "9. ve 10. Kisim Istanbul Kultur",
      "Universitesi D-100 Yanyol K:-1",
      "Istanbul - Avrupa, 34 34158",
    ],
    mop: { ready: false, wait: null },
    schedule: [
      {
        dayName: "Today",
        hours: "7:30 AM to 5:30 PM",
        open: true,
        holiday: "",
      },
      { dayName: "Tomorrow", hours: "Closed", open: false, holiday: "" },
      { dayName: "Sunday", hours: "Closed", open: false, holiday: "" },
      {
        dayName: "Monday",
        hours: "7:30 AM to 5:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tuesday",
        hours: "7:30 AM to 5:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Wednesday",
        hours: "7:30 AM to 5:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Thursday",
        hours: "7:30 AM to 5:30 PM",
        open: true,
        holiday: "",
      },
    ],
    features: [],
    slug: "starbucks-9-ve-10-kisim-istanbul-kultur-istanbul-avrupa-34-3",
  },
  {
    recommendation: {},
    storeNumber: "32127-107321",
    id: "5975",
    name: "Starbucks",
    phoneNumber: "0 212 669 82 36",
    coordinates: { latitude: 41.063004, longitude: 28.686369 },
    regulations: [],
    address: {
      streetAddressLine1: "Derekoy Mevkii Suzer Bulv. 3. Cad.",
      streetAddressLine2: "Sehr-i Bazaar Alisveris Merk G Blok D:11",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34555",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: true,
    openStatusText: "Open until 12:00 AM",
    addressLines: [
      "Derekoy Mevkii Suzer Bulv. 3. Cad.",
      "Sehr-i Bazaar Alisveris Merk G Blok D:11",
      "Istanbul, 34 34555",
    ],
    mop: { ready: false, wait: null },
    schedule: [
      {
        dayName: "Today",
        hours: "8:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tomorrow",
        hours: "8:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sunday",
        hours: "8:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Monday",
        hours: "8:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tuesday",
        hours: "8:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Wednesday",
        hours: "8:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Thursday",
        hours: "8:00 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
    ],
    features: [],
    slug: "starbucks-derekoy-mevkii-suzer-bulv-3-cad-istanbul-34-34555-",
  },
  {
    recommendation: {},
    storeNumber: "16015-167505",
    id: "63279",
    name: "Starbucks",
    phoneNumber: "0.212.559 44 43",
    coordinates: { latitude: 40.974483, longitude: 28.869221 },
    regulations: [],
    address: {
      streetAddressLine1: "1. Kisim Rauf Orbay Cad. Bakirkoy Sahil",
      streetAddressLine2: "Yolu Galleria Alisveris Merk. No:6 D:2/A",
      streetAddressLine3: null,
      city: "Istanbul - Avrupa",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34158",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: true,
    openStatusText: "Open until 12:00 AM",
    addressLines: [
      "1. Kisim Rauf Orbay Cad. Bakirkoy Sahil",
      "Yolu Galleria Alisveris Merk. No:6 D:2/A",
      "Istanbul - Avrupa, 34 34158",
    ],
    mop: { ready: false, wait: null },
    schedule: [
      {
        dayName: "Today",
        hours: "7:30 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tomorrow",
        hours: "7:30 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sunday",
        hours: "7:30 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Monday",
        hours: "7:30 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tuesday",
        hours: "7:30 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Wednesday",
        hours: "7:30 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Thursday",
        hours: "7:30 AM to 12:00 AM",
        open: true,
        holiday: "",
      },
    ],
    features: [],
    slug: "starbucks-1-kisim-rauf-orbay-cad-bakirkoy-sahil-istanbul-avr",
  },
  {
    recommendation: {},
    storeNumber: "48656-264347",
    id: "1015501",
    name: "Atakoy Marina",
    phoneNumber: null,
    coordinates: { latitude: 40.971425, longitude: 28.874485 },
    regulations: [],
    address: {
      streetAddressLine1: "Atakoy 1. Mah. Atakoy Marina",
      streetAddressLine2: "Bakirkoy",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "00000",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Atakoy 1. Mah. Atakoy Marina",
      "Bakirkoy",
      "Istanbul, 34 00000",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "atakoy-marina-atakoy-1-mah-atakoy-marina-istanbul-34-00000-tr",
  },
  {
    recommendation: {},
    storeNumber: "27600-248065",
    id: "1012348",
    name: "Ataturk Airport Mezzanine",
    phoneNumber: null,
    coordinates: { latitude: 40.978531, longitude: 28.86446 },
    regulations: [],
    address: {
      streetAddressLine1: "Ataturk Airport",
      streetAddressLine2: "Yesilkoy, Bakirkoy",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34149",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Ataturk Airport",
      "Yesilkoy, Bakirkoy",
      "Istanbul, 34 34149",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "ataturk-airport-mezzanine-ataturk-airport-istanbul-34-34149-tr",
  },
  {
    recommendation: {},
    storeNumber: "26146-243746",
    id: "1011518",
    name: "Acibadem Hospital Bakirkoy",
    phoneNumber: null,
    coordinates: { latitude: 40.976292, longitude: 28.8724 },
    regulations: [],
    address: {
      streetAddressLine1: "Zeytinlik Mah. Halit Ziya Usakligil Cad.",
      streetAddressLine2: "Carousel AVM Bakirkoy",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34710",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Zeytinlik Mah. Halit Ziya Usakligil Cad.",
      "Carousel AVM Bakirkoy",
      "Istanbul, 34 34710",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "acibadem-hospital-bakirkoy-zeytinlik-mah-halit-ziya-usakligil-cad-istanbul-34",
  },
  {
    recommendation: {},
    storeNumber: "32128-118704",
    id: "5920",
    name: "Starbucks",
    phoneNumber: "0212 559 70 26",
    coordinates: { latitude: 40.977608, longitude: 28.871161 },
    regulations: [],
    address: {
      streetAddressLine1: "1. Kisim Mah. Fisekhane Cad. Capacity",
      streetAddressLine2: "Alisveris Merkezi No:7 K:1 D:36",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34158",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: true,
    openStatusText: "Closes in 57 mins",
    addressLines: [
      "1. Kisim Mah. Fisekhane Cad. Capacity",
      "Alisveris Merkezi No:7 K:1 D:36",
      "Istanbul, 34 34158",
    ],
    mop: { ready: false, wait: null },
    schedule: [
      {
        dayName: "Today",
        hours: "7:30 AM to 8:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tomorrow",
        hours: "10:00 AM to 6:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sunday",
        hours: "12:00 PM to 8:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Monday",
        hours: "7:30 AM to 8:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tuesday",
        hours: "7:30 AM to 8:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Wednesday",
        hours: "7:30 AM to 8:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Thursday",
        hours: "7:30 AM to 8:30 PM",
        open: true,
        holiday: "",
      },
    ],
    features: [],
    slug: "starbucks-1-kisim-mah-fisekhane-cad-capacity-istanbul-34-341",
  },
  {
    recommendation: {},
    storeNumber: "51037-276973",
    id: "1018029",
    name: "Carousel Teras",
    phoneNumber: null,
    coordinates: { latitude: 40.977778, longitude: 28.873539 },
    regulations: [],
    address: {
      streetAddressLine1: "Halit Ziya Usakligil Cad.",
      streetAddressLine2: "No. 1",
      streetAddressLine3: null,
      city: "Bakirkoy",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34710",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: ["Halit Ziya Usakligil Cad.", "No. 1", "Bakirkoy, 34 34710"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "carousel-teras-halit-ziya-usakligil-cad-bakirkoy-34-34710-tr",
  },
  {
    recommendation: {},
    storeNumber: "31924-116727",
    id: "5935",
    name: "Starbucks",
    phoneNumber: "0 224 241 27 60",
    coordinates: { latitude: 40.250585, longitude: 28.958833 },
    regulations: [],
    address: {
      streetAddressLine1: "Mudanya Yolu 9. Km. Korupark Alisveris",
      streetAddressLine2: "Merkezi No:2 K:Zemin D:42",
      streetAddressLine3: null,
      city: "Bursa",
      countrySubdivisionCode: "16",
      countryCode: "TR",
      postalCode: "16000",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: true,
    openStatusText: "Open until 11:00 PM",
    addressLines: [
      "Mudanya Yolu 9. Km. Korupark Alisveris",
      "Merkezi No:2 K:Zemin D:42",
      "Bursa, 16 16000",
    ],
    mop: { ready: false, wait: null },
    schedule: [
      {
        dayName: "Today",
        hours: "8:30 AM to 11:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tomorrow",
        hours: "8:30 AM to 11:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sunday",
        hours: "8:30 AM to 11:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Monday",
        hours: "8:30 AM to 11:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tuesday",
        hours: "8:30 AM to 11:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Wednesday",
        hours: "8:30 AM to 11:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Thursday",
        hours: "8:30 AM to 11:00 PM",
        open: true,
        holiday: "",
      },
    ],
    features: [],
    slug: "starbucks-mudanya-yolu-9-km-korupark-alisveris-bursa-16-1600",
  },
  {
    recommendation: {},
    storeNumber: "50433-274724",
    id: "1017837",
    name: "Bursa Ozdilek Park",
    phoneNumber: null,
    coordinates: { latitude: 40.212662, longitude: 28.918203 },
    regulations: [],
    address: {
      streetAddressLine1: "Ertugrul mah Yeni Yalova",
      streetAddressLine2: "Yolu 4. Km nilufer",
      streetAddressLine3: null,
      city: "Bursa",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "16120",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Ertugrul mah Yeni Yalova",
      "Yolu 4. Km nilufer",
      "Bursa, 34 16120",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "bursa-ozdilek-park-ertugrul-mah-yeni-yalova-bursa-34-16120-tr",
  },
  {
    recommendation: {},
    storeNumber: "54149-286395",
    id: "1020523",
    name: "Memorial Bahcelievler",
    phoneNumber: null,
    coordinates: { latitude: 40.992902, longitude: 28.852826 },
    regulations: [],
    address: {
      streetAddressLine1: "Atakoy kavsagi d-100 yanyolu",
      streetAddressLine2: "Bahcelievler",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34180",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Atakoy kavsagi d-100 yanyolu",
      "Bahcelievler",
      "Istanbul, 34 34180",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug:
      "memorial-bahcelievler-atakoy-kavsagi-d-100-yanyolu-istanbul-34-34180-tr",
  },
  {
    recommendation: {},
    storeNumber: "22700-223745",
    id: "1007060",
    name: "Starbucks",
    phoneNumber: null,
    coordinates: { latitude: 41.034491, longitude: 28.778675 },
    regulations: [],
    address: {
      streetAddressLine1: "Merkez Mah. Turgut Ozal Bulv.",
      streetAddressLine2: "No:16",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34303",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Merkez Mah. Turgut Ozal Bulv.",
      "No:16",
      "Istanbul, 34 34303",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "starbucks-merkez-mah-turgut-ozal-bulv-istanbul-34-34303-tr",
  },
  {
    recommendation: {},
    storeNumber: "52275-281285",
    id: "1019018",
    name: "Ispartakule",
    phoneNumber: null,
    coordinates: { latitude: 41.064078, longitude: 28.712989 },
    regulations: [],
    address: {
      streetAddressLine1: "Faruk Nafiz Camlibel Cad. No. 2AA",
      streetAddressLine2: "Avcilar",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "33",
      countryCode: "TR",
      postalCode: "34325",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Faruk Nafiz Camlibel Cad. No. 2AA",
      "Avcilar",
      "Istanbul, 33 34325",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "ispartakule-faruk-nafiz-camlibel-cad-no-2-aa-istanbul-33-34325",
  },
  {
    recommendation: {},
    storeNumber: "30872-101240",
    id: "5959",
    name: "Starbucks",
    phoneNumber: "00902125715250",
    coordinates: { latitude: 40.983265, longitude: 28.872263 },
    regulations: [],
    address: {
      streetAddressLine1: "Incirli Cad. Town Center",
      streetAddressLine2: "No:11 K:Giris D:208",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34147",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: true,
    openStatusText: "Open until 11:30 PM",
    addressLines: [
      "Incirli Cad. Town Center",
      "No:11 K:Giris D:208",
      "Istanbul, 34 34147",
    ],
    mop: { ready: false, wait: null },
    schedule: [
      {
        dayName: "Today",
        hours: "7:30 AM to 11:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tomorrow",
        hours: "7:30 AM to 11:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sunday",
        hours: "7:30 AM to 11:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Monday",
        hours: "7:30 AM to 11:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tuesday",
        hours: "7:30 AM to 11:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Wednesday",
        hours: "7:30 AM to 11:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Thursday",
        hours: "7:30 AM to 11:30 PM",
        open: true,
        holiday: "",
      },
    ],
    features: [],
    slug: "starbucks-incirli-cad-town-center-istanbul-34-34147-tr",
  },
  {
    recommendation: {},
    storeNumber: "55906-289769",
    id: "1022295",
    name: "TEMA ISTANBUL",
    phoneNumber: null,
    coordinates: { latitude: 41.051518, longitude: 28.76209 },
    regulations: [],
    address: {
      streetAddressLine1: "221 Sokak",
      streetAddressLine2: "Tema Carsi Atakent Kucukcekmece",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34307",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "221 Sokak",
      "Tema Carsi Atakent Kucukcekmece",
      "Istanbul, 34 34307",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "tema-istanbul-221-sokak-istanbul-34-34307-tr",
  },
  {
    recommendation: {},
    storeNumber: "19611-199665",
    id: "1007725",
    name: "Starbucks",
    phoneNumber: null,
    coordinates: { latitude: 41.025358, longitude: 28.815679 },
    regulations: [],
    address: {
      streetAddressLine1: "Yalcin Kores Caddesi Cavdar",
      streetAddressLine2: null,
      streetAddressLine3: "Sokak No:1 Bagcilar",
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34212",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: ["Yalcin Kores Caddesi Cavdar", "Istanbul, 34 34212"],
    mop: { ready: false, wait: null },
    features: [],
    slug: "starbucks-yalcin-kores-caddesi-cavdar-sokak-no-1-bagcilar-is",
  },
  {
    recommendation: {},
    storeNumber: "32231-127964",
    id: "5918",
    name: "Starbucks",
    phoneNumber: "0212 489 24 70",
    coordinates: { latitude: 41.028464, longitude: 28.812257 },
    regulations: [],
    address: {
      streetAddressLine1: "Kocman Cad. Ziyal Plaza No:54 D:3",
      streetAddressLine2: null,
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34500",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: true,
    openStatusText: "Open until 9:00 PM",
    addressLines: ["Kocman Cad. Ziyal Plaza No:54 D:3", "Istanbul, 34 34500"],
    mop: { ready: false, wait: null },
    schedule: [
      {
        dayName: "Today",
        hours: "7:00 AM to 9:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tomorrow",
        hours: "10:00 AM to 6:30 PM",
        open: true,
        holiday: "",
      },
      { dayName: "Sunday", hours: "Closed", open: false, holiday: "" },
      {
        dayName: "Monday",
        hours: "7:00 AM to 9:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tuesday",
        hours: "7:00 AM to 9:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Wednesday",
        hours: "7:00 AM to 9:00 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Thursday",
        hours: "7:00 AM to 9:00 PM",
        open: true,
        holiday: "",
      },
    ],
    features: [],
    slug: "starbucks-kocman-cad-ziyal-plaza-no-54-d-3-istanbul-34-34500",
  },
  {
    recommendation: {},
    storeNumber: "15826-165247",
    id: "65777",
    name: "Starbucks",
    phoneNumber: "0212 466 67 39",
    coordinates: { latitude: 40.991715, longitude: 28.88738 },
    regulations: [],
    address: {
      streetAddressLine1: "Osmaniye Mah. Cobancesme Kosuuyolu Bulva",
      streetAddressLine2: "Marmara Forum AVM No. MS Block 16",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34144",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: true,
    openStatusText: "Open until 9:30 PM",
    addressLines: [
      "Osmaniye Mah. Cobancesme Kosuuyolu Bulva",
      "Marmara Forum AVM No. MS Block 16",
      "Istanbul, 34 34144",
    ],
    mop: { ready: false, wait: null },
    schedule: [
      {
        dayName: "Today",
        hours: "10:00 AM to 9:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tomorrow",
        hours: "10:00 AM to 9:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Sunday",
        hours: "10:00 AM to 9:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Monday",
        hours: "10:00 AM to 9:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Tuesday",
        hours: "10:00 AM to 9:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Wednesday",
        hours: "10:00 AM to 9:30 PM",
        open: true,
        holiday: "",
      },
      {
        dayName: "Thursday",
        hours: "10:00 AM to 9:30 PM",
        open: true,
        holiday: "",
      },
    ],
    features: [],
    slug: "starbucks-osmaniye-mah-cobancesme-kosuuyolu-bulva-istanbul-3",
  },
  {
    recommendation: {},
    storeNumber: "50190-273468",
    id: "1017520",
    name: "Oasis Gunesli",
    phoneNumber: null,
    coordinates: { latitude: 41.04031, longitude: 28.81127 },
    regulations: [],
    address: {
      streetAddressLine1: "Evren Mah. Bahar Cd. 43-J,",
      streetAddressLine2: "Gunesli Bagcilar",
      streetAddressLine3: null,
      city: "Istanbul",
      countrySubdivisionCode: "34",
      countryCode: "TR",
      postalCode: "34200",
    },
    timeZoneInfo: {
      currentTimeOffset: 180,
      windowsTimeZoneId: "Turkey Standard Time",
      olsonTimeZoneId: "GMT+000000 Europe/Istanbul",
    },
    brandName: "Starbucks",
    ownershipTypeCode: "LS",
    open: null,
    openStatusText: "",
    addressLines: [
      "Evren Mah. Bahar Cd. 43-J,",
      "Gunesli Bagcilar",
      "Istanbul, 34 34200",
    ],
    mop: { ready: false, wait: null },
    features: [],
    slug: "oasis-gunesli-evren-mah-bahar-cd-43-j-istanbul-34-34200-tr",
  },
];
